baseURL: https://polectron.xyz/
languageCode: en-us
title: Polectron's Tech Blog
theme: ["PaperMod"]
params:
  homeInfoParams:
    Title: Hi! ðŸ¯
    Content: > 
      - My name is Daniel RÃ¼ckert a.k.a polectron. I'm a backend engineer at [Plexigrid](https://plexigrid.com/).
      
      - This blog will primarily be a repository for scripts and research I've conducted, which I hope will also be useful to others.
  cover:
    responsiveImages: true
    linkFullImages: false
# menu:
#   main:
#     - identifier: categories
#       name: categories
#       url: /categories/
#       weight: 10
#     - identifier: tags
#       name: tags
#       url: /tags/
#       weight: 20
#     - identifier: example
#       name: example.org
#       url: https://example.org
#       weight: 30